### ISSUE TITLE
rename this repo "helm-charts" -> "helm-chart"

### ISSUE THREAD

**Issue by venkatamutyala** [onetimesecret/helm-chart#2]
Hey @onetimesecret can you rename this repo from "helm-chart" -> "helm-charts" ? 

There will only be one chart to start off. So when there is a need for multiple we can always create a new repo as needed

**Comment by venkatamutyala** [comment]
Hey @delano any thoughts?

**Comment by delano** [comment]
> Hey https://github.com/onetimesecret can you rename this repo from "helm-chart" -> "helm-charts" ?

Hey, just to confirm. Plural or singular?

**Comment by venkatamutyala** [comment]
@delano Signular.

new repo name should be: `github.com/onetimesecret/helm-chart`

**Comment by delano** [comment]
We achieved the singularity.
